/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import restock.barang;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;


/**
 *
 * @author USER
 */
public class frameBarang extends javax.swing.JFrame {
    
    private barang CRUD;

    /**
     * Creates new form frameBarang
     */
    public frameBarang() {
        
        CRUD = new barang();
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKodeBarang = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORM BARANG");

        jLabel1.setText("Kode Barang");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Stok");

        jLabel4.setText("Harga");

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ubah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKodeBarang)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStok)
                    .addComponent(txtHarga)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        // KODE TOMBOL SIMPAN BARANG
        try {
            
            if(txtKodeBarang.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Kode Barang Belum Diisi!");
                txtKodeBarang.requestFocus();
            } else if(txtNamaBarang.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Nama Barang Belum Diisi!");
                txtNamaBarang.requestFocus();
            } else if(txtStok.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Stok Belum Diisi!");
                txtStok.requestFocus();
            } else if(txtHarga.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Harga Belum Diisi!");
                txtHarga.requestFocus();
            } else {
                
                int kodeBarang = Integer.parseInt(txtKodeBarang.getText());
                int stok = Integer.parseInt(txtStok.getText());
                int harga = Integer.parseInt(txtHarga.getText());
                
                CRUD.simpanBarang(kodeBarang, txtNamaBarang.getText(), stok, harga);
                JOptionPane.showMessageDialog(this, "Barang Berhasil Disimpan!");
            }
        
        } catch (NumberFormatException e) {
          
            JOptionPane.showMessageDialog(this, "Harap masukkan nilai numerik yang valid untuk Kode Barang, Stok, dan Harga.");
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this,"Barang Gagal Disimpan: " + e.getMessage());
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        // KODE TOMBOL UBAH BARANG
        try {
            
            if  (
                    txtKodeBarang.getText().equals("") &&
                    txtNamaBarang.getText().equals("") &&
                    txtStok.getText().equals("") &&
                    txtHarga.getText().equals("")
                )      
            {
                JOptionPane.showMessageDialog(this, "Silahkan Cari Data Terlebih Dahulu!");
                txtKodeBarang.requestFocus();
            } else {
                int kodeBarang = Integer.parseInt(txtKodeBarang.getText());
                int stok = Integer.parseInt(txtStok.getText());
                int harga = Integer.parseInt(txtHarga.getText());
                
                CRUD.ubahBarang(kodeBarang, txtNamaBarang.getText(), stok, harga);
                JOptionPane.showMessageDialog(this, "Barang Berhasil Diubah!");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harap masukkan nilai numerik yang valid untuk Kode Barang, Stok, dan Harga.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Barang Gagal Diubah: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // KODE TOMBOL CARI BARANG
        try {
            
            String sql = "SELECT * FROM barang WHERE kode_barang = '"+txtKodeBarang.getText()+"'";
            Statement perintah = crud.Koneksi.koneksidb.createStatement();
            ResultSet data = perintah.executeQuery(sql);
            if (data.next()) {
                String strStok = String.valueOf(data.getInt("stok"));
                String strHarga = String.valueOf(data.getInt("harga"));
                
                txtNamaBarang.setText(data.getString("nama_barang"));
                txtStok.setText(strStok);
                txtHarga.setText(strHarga);
            } else {
                txtNamaBarang.setText(null);
                txtStok.setText(null);
                txtHarga.setText(null);
                JOptionPane.showMessageDialog(this, "Data yang Anda Cari Tidak Ditemukan!");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        // KODE TOMBOL HAPUS BARANG
        try {
            if  (
                    txtKodeBarang.getText().equals("") &&
                    txtNamaBarang.getText().equals("") &&
                    txtStok.getText().equals("") &&
                    txtHarga.getText().equals("")
                )      
            {
                JOptionPane.showMessageDialog(this, "Silahkan Cari Data Terlebih Dahulu!");
                txtKodeBarang.requestFocus();
            } else {
                int kodeBarang = Integer.parseInt(txtKodeBarang.getText());
                CRUD.hapusBarang(kodeBarang);
                JOptionPane.showMessageDialog(this, "Barang Berhasil Dihapus!");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harap masukkan nilai numerik yang valid untuk Kode Barang, Stok, dan Harga.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Barang Gagal Dihapus: " + e.getMessage());
        } 
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
