/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import restock.penjualan;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;


/**
 *
 * @author USER
 */
public class framePenjualan extends javax.swing.JFrame {

    private penjualan CRUD;
    
    /**
     * Creates new form framePenjualan
     */
    public framePenjualan() {
        
        CRUD = new penjualan();
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNoKeluar = new javax.swing.JTextField();
        txtTanggalKeluar = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtKodeBarang = new javax.swing.JTextField();
        txtKodePelanggan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORM PENJUALAN");

        jLabel1.setText("No Keluar");

        jLabel2.setText("Tanggal Keluar");

        jLabel3.setText("Jumlah");

        jLabel4.setText("Total");

        jLabel5.setText("Kode Barang");

        jLabel6.setText("Kode Pelanggan");

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ubah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNoKeluar)
                            .addComponent(txtTanggalKeluar)
                            .addComponent(txtJumlah)
                            .addComponent(txtTotal)
                            .addComponent(txtKodeBarang)
                            .addComponent(txtKodePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNoKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtTanggalKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtKodePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // KODE TOMBOL CARI PENJUALAN
        try {
            
            String sql = "SELECT * FROM penjualan WHERE no_keluar = '"+txtNoKeluar.getText()+"'";
            Statement perintah = crud.Koneksi.koneksidb.createStatement();
            ResultSet data = perintah.executeQuery(sql);
            if (data.next()) {
                String strTglKeluar = String.valueOf(data.getDate("tgl_keluar"));
                String strJumlah = String.valueOf(data.getInt("jumlah"));
                String strTotal = String.valueOf(data.getInt("total"));
                String strKodeBarang = String.valueOf(data.getInt("kode_barang"));
                String strKodePelanggan = String.valueOf(data.getInt("kode_pelanggan"));
                
                txtTanggalKeluar.setText(strTglKeluar);
                txtJumlah.setText(strJumlah);
                txtTotal.setText(strTotal);
                txtKodeBarang.setText(strKodeBarang);
                txtKodePelanggan.setText(strKodePelanggan);
            } else {
                txtTanggalKeluar.setText(null);
                txtJumlah.setText(null);
                txtTotal.setText(null);
                txtKodeBarang.setText(null);
                txtKodePelanggan.setText(null);
                JOptionPane.showMessageDialog(this, "Data yang Anda Cari Tidak Ditemukan!");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        // KODE TOMBOL SIMPAN PENJUALAN
        try {
            
            if(txtNoKeluar.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "No Keluar Belum Diisi!");
                txtNoKeluar.requestFocus();
            } else if(txtTanggalKeluar.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Tanggal Keluar Belum Diisi!");
                txtTanggalKeluar.requestFocus();
            } else if(txtJumlah.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Jumlah Belum Diisi!");
                txtJumlah.requestFocus();
            } else if(txtTotal.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Total Belum Diisi!");
                txtJumlah.requestFocus();
            } else if(txtKodeBarang.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Kode Barang Belum Diisi!");
                txtKodeBarang.requestFocus();
            } else if(txtKodePelanggan.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Kode Pelanggan Belum Diisi!");
                txtKodePelanggan.requestFocus();
            } else {
                int noKeluar = Integer.parseInt(txtNoKeluar.getText());
                int jumlah = Integer.parseInt(txtJumlah.getText());
                int total = Integer.parseInt(txtTotal.getText());
                int kodeBarang = Integer.parseInt(txtKodeBarang.getText());
                int kodePelanggan = Integer.parseInt(txtKodePelanggan.getText());
                
                CRUD.simpanPenjualan(noKeluar, txtTanggalKeluar.getText(), jumlah, total, kodeBarang, kodePelanggan);
                JOptionPane.showMessageDialog(this, "Data Penjualan Berhasil Disimpan!");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harap masukkan nilai numerik yang valid untuk [No Keluar, Jumlah, Total, Kode Barang, Kode Pelanggan]" + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Penjualan Gagal Disimpan: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        // KODE TOMBOL UBAH PENJUALAN
        try {
            
            if (
                    txtNoKeluar.getText().equals("") &&
                    txtTanggalKeluar.getText().equals("") &&
                    txtJumlah.getText().equals("") &&
                    txtTotal.getText().equals("") &&
                    txtKodeBarang.getText().equals("") &&
                    txtKodePelanggan.getText().equals("")
               )
            {
                JOptionPane.showMessageDialog(this, "Silahkan Cari Data Terlebih Dahulu!");
                txtNoKeluar.requestFocus();
            } else {
                int noKeluar = Integer.parseInt(txtNoKeluar.getText());
                int jumlah = Integer.parseInt(txtJumlah.getText());
                int total = Integer.parseInt(txtTotal.getText());
                int kodeBarang = Integer.parseInt(txtKodeBarang.getText());
                int kodePelanggan = Integer.parseInt(txtKodePelanggan.getText());
                
                CRUD.ubahPenjualan(noKeluar, txtTanggalKeluar.getText(), jumlah, total, kodeBarang, kodePelanggan);
                JOptionPane.showMessageDialog(this, "Data Penjualan Berhasil Diubah!");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harap masukkan nilai numerik yang valid untuk [No Masuk, Kode Supplier, Kode Barang, Jumlah, Total.]" + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Penjualan Gagal Diubah: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        // KODE TOMBOL HAPUS BARANG
        try {
            
            if  (
                    txtNoKeluar.getText().equals("") &&
                    txtTanggalKeluar.getText().equals("") &&
                    txtJumlah.getText().equals("") &&
                    txtTotal.getText().equals("") &&
                    txtKodeBarang.getText().equals("") &&
                    txtKodePelanggan.getText().equals("")
                )      
            {
                JOptionPane.showMessageDialog(this, "Silahkan Cari Data Terlebih Dahulu!");
                txtNoKeluar.requestFocus();
            } else {
                int noKeluar = Integer.parseInt(txtNoKeluar.getText());
                CRUD.hapusPenjualan(noKeluar);
                JOptionPane.showMessageDialog(this, "Data Penjualan Berhasil Dihapus!");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harap masukkan nilai numerik yang valid untuk No Keluar.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Data Penjualan Gagal Dihapus: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtKodePelanggan;
    private javax.swing.JTextField txtNoKeluar;
    private javax.swing.JTextField txtTanggalKeluar;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
