/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import restock.pembelian;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author USER
 */
public class framePembelian extends javax.swing.JFrame {

    private pembelian CRUD;
    
    /**
     * Creates new form framePembelian
     */
    public framePembelian() {
        
        CRUD = new pembelian();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNoMasuk = new javax.swing.JTextField();
        txtTanggalMasuk = new javax.swing.JTextField();
        txtKodeSupplier = new javax.swing.JTextField();
        txtKodeBarang = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORM PEMBELIAN");

        jLabel1.setText("No Masuk");

        jLabel2.setText("Tanggal Masuk");

        jLabel3.setText("Kode Supplier");

        jLabel4.setText("Kode Barang");

        jLabel5.setText("Jumlah");

        jLabel6.setText("Total");

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ubah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal)
                            .addComponent(txtJumlah)
                            .addComponent(txtKodeBarang)
                            .addComponent(txtKodeSupplier)
                            .addComponent(txtTanggalMasuk)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtNoMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // KODE TOMBOL CARI PEMBELIAN
        try {
            
            String sql = "SELECT * FROM pembelian WHERE no_masuk = '"+txtNoMasuk.getText()+"'";
            Statement perintah = crud.Koneksi.koneksidb.createStatement();
            ResultSet data = perintah.executeQuery(sql);
            if (data.next()) {
                String strTglMasuk = String.valueOf(data.getDate("tgl_masuk"));
                String strKodeSup = String.valueOf(data.getInt("kode_sup"));
                String strKodeBar = String.valueOf(data.getInt("kode_barang"));
                String strJumlah = String.valueOf(data.getInt("jumlah"));
                String strTotal = String.valueOf(data.getInt("total"));
                
                txtTanggalMasuk.setText(strTglMasuk);
                txtKodeSupplier.setText(strKodeSup);
                txtKodeBarang.setText(strKodeBar);
                txtJumlah.setText(strJumlah);
                txtTotal.setText(strTotal);
            } else {
                txtTanggalMasuk.setText(null);
                txtKodeSupplier.setText(null);
                txtKodeBarang.setText(null);
                txtJumlah.setText(null);
                txtTotal.setText(null);
                JOptionPane.showMessageDialog(this, "Data yang Anda Cari Tidak Ditemukan!");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        // KODE TOMBOL SIMPAN PEMBELIAN
        try {
            
            if(txtNoMasuk.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "No Masuk Belum Diisi!");
                txtNoMasuk.requestFocus();
            } else if(txtTanggalMasuk.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Tanggal Masuk Belum Diisi!");
                txtTanggalMasuk.requestFocus();
            } else if(txtKodeSupplier.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Kode Supplier Belum Diisi!");
                txtKodeSupplier.requestFocus();
            } else if(txtKodeBarang.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Kode Barang Belum Diisi!");
                txtKodeBarang.requestFocus();
            } else if(txtJumlah.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Jumlah Belum Diisi!");
                txtJumlah.requestFocus();
            } else if(txtTotal.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Jumlah Belum Diisi!");
                txtTotal.requestFocus();
            } else {
                int noMasuk = Integer.parseInt(txtNoMasuk.getText());
                int kodeSupplier = Integer.parseInt(txtKodeSupplier.getText());
                int kodeBarang = Integer.parseInt(txtKodeBarang.getText());
                int jumlah = Integer.parseInt(txtJumlah.getText());
                int total = Integer.parseInt(txtTotal.getText());
                
                CRUD.simpanPembelian(noMasuk, txtTanggalMasuk.getText(), kodeSupplier, kodeBarang, jumlah, total);
                JOptionPane.showMessageDialog(this, "Data Pembelian Berhasil Disimpan!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harap masukkan nilai numerik yang valid untuk [No Masuk, Kode Supplier, Kode Barang, Jumlah, Total.]" + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Pembelian Gagal Disimpan: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        // KODE TOMBOL UBAH PEMBELIAN
        try {
            
            if (
                    txtNoMasuk.getText().equals("") &&
                    txtTanggalMasuk.getText().equals("") &&
                    txtKodeSupplier.getText().equals("") &&
                    txtKodeBarang.getText().equals("") &&
                    txtJumlah.getText().equals("") &&
                    txtTotal.getText().equals("")
               )
            {
                JOptionPane.showMessageDialog(this, "Silahkan Cari Data Terlebih Dahulu!");
                txtNoMasuk.requestFocus();
            } else {
                int noMasuk = Integer.parseInt(txtNoMasuk.getText());
                int kodeSupplier = Integer.parseInt(txtKodeSupplier.getText());
                int kodeBarang = Integer.parseInt(txtKodeBarang.getText());
                int jumlah = Integer.parseInt(txtJumlah.getText());
                int total = Integer.parseInt(txtTotal.getText());
                
                CRUD.ubahPembelian(noMasuk, txtTanggalMasuk.getText(), kodeSupplier, kodeBarang, jumlah, total);
                JOptionPane.showMessageDialog(this, "Data Pembelian Berhasil Diubah!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harap masukkan nilai numerik yang valid untuk [No Masuk, Kode Supplier, Kode Barang, Jumlah, Total.]" + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Pembelian Gagal Diubah: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        // KODE TOMBOL HAPUS PEMBELIAN
        try {
            
            if  (
                    txtNoMasuk.getText().equals("") &&
                    txtTanggalMasuk.getText().equals("") &&
                    txtKodeSupplier.getText().equals("") &&
                    txtKodeBarang.getText().equals("") &&
                    txtJumlah.getText().equals("") &&
                    txtTotal.getText().equals("")
                )      
            {
                JOptionPane.showMessageDialog(this, "Silahkan Cari Data Terlebih Dahulu!");
                txtNoMasuk.requestFocus();
            } else {
                int noMasuk = Integer.parseInt(txtNoMasuk.getText());
                CRUD.hapusPembelian(noMasuk);
                JOptionPane.showMessageDialog(this, "Data Pembelian Berhasil Dihapus!");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harap masukkan nilai numerik yang valid untuk No Masuk.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Data Pembelian Gagal Dihapus: " + e.getMessage());
        } 
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtKodeSupplier;
    private javax.swing.JTextField txtNoMasuk;
    private javax.swing.JTextField txtTanggalMasuk;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
